# Generated by Django 5.0 on 2024-06-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_date',
            field=models.DateField(null=True),
        ),
    ]
